name: nHandCuff
version: '${project.version}'
main: n2k.nhandcuff.nHandCuff
api-version: 1.17
authors: [ n2k ]
commands:
  handcuff:
    description: The main command.
permissions:
  nhandcuff.*:
    children:
      - nhandcuff.use
      - nhandcuff.admin
      - nhandcuff.bypass
softdepend:
  - JSONConfigAPI
